name: Move PR to Needs Review

on:
  pull_request:
    types: [opened, reopened, review_requested, ready_for_review, review_request_removed]

jobs:
  move_pr_to_needs_review:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PROJECT_BOARD_AUTOMATION_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move PR to Needs Review column
        env:
#          GH_TOKEN: ${{ secrets.PROJECT_BOARD_AUTOMATION_TOKEN }}
          PROJECT_ID: 1
        run: |
          PR_NUMBER=$(jq -r .pull_request.number < "$GITHUB_EVENT_PATH")
          COLUMN_NAME="Needs review"
          
          # Get the column ID
          COLUMN_ID=$(gh api graphql -f query='
          query($id: ID!) {
            node(id: $id) {
              ... on ProjectV2 {
                fields(first: 20) {
                  nodes {
                    ... on ProjectV2Field {
                      name
                      id
                    }
                  }
                }
              }
            }
          }' -F id="$PROJECT_ID" -q ".data.node.fields.nodes[] | select(.name == \"$COLUMN_NAME\") | .id")
          
          # Add the PR to the column
          gh api graphql -f query='
          mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!) {
            updateProjectV2ItemField(input: {projectId: $projectId, itemId: $itemId, fieldId: $fieldId, value: "Needs review"}) {
              clientMutationId
            }
          }' -F projectId="$PROJECT_ID" -F itemId="$PR_NUMBER" -F fieldId="$COLUMN_ID"
