name: Release Workflow

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Build tarball
        run: sbt createTarball
      - name: Upload Release Asset
        uses: actions/upload-artifact@v2
        with:
         name: unitycatalog
         path: target/unitycatalog-*.tar.gz
