# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: SBT Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run tests
      run: sbt test
    - name: Run license check
      run: sbt licenseCheck
    - name: Run tests with coverage
      run: sbt jacoco

  generate-validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'

    - name: Generate OpenAPI Client and Model classes
      run: sbt generate

    - name: Check Client Differences
      run: |
        git diff --name-only clients/java > /tmp/client_diff.txt
        if [[ -s /tmp/client_diff.txt ]]; then
          echo "Generated files do not match committed files."
          cat /tmp/client_diff.txt
          exit 1
        fi
      shell: bash

    - name: Check Server Model Differences
      run: |
        git diff --name-only server/src/main/java/io/unitycatalog/server/model > /tmp/server_diff.txt
        if [[ -s /tmp/server_diff.txt ]]; then
          echo "Generated files do not match committed files."
          cat /tmp/server_diff.txt
          exit 1
        fi
      shell: bash