# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: SBT Tasks

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run tests
      run: sbt test
    - name: Run license check
      run: sbt licenseCheck
    - name: Run tests with coverage
      run: sbt jacoco

  generated-files-validation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'

    - name: Generate OpenAPI Client and Server Model classes
      run: sbt generate

    - name: Check Generated Files Differences
      run: |
        CLIENT_DIFF=$(git diff --name-only clients/java)
        SERVER_DIFF=$(git diff --name-only server/src/main/java/io/unitycatalog/server/model)
        
        if [[ -n $CLIENT_DIFF || -n $SERVER_DIFF ]]; then
          echo "This PR contains changes to generated files. Making changes to generated files is not allowed."
          echo "If this is intended for some reason, please speak to the project maintainers."
          echo "Please revert or run 'sbt generate' locally and commit the changes."
          if [[ -n $CLIENT_DIFF ]]; then
            echo "Modified client files:"
            echo "$CLIENT_DIFF"
          fi
          if [[ -n $SERVER_DIFF ]]; then
            echo "Modified server model files:"
            echo "$SERVER_DIFF"
          fi
          exit 1
        fi
      shell: bash