name: Tutorial Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  scala-java-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Compile Project
        run: build/sbt compile

  python-tests:
    runs-on: ubuntu-latest
    needs: scala-java-build  # This ensures python-tests runs only after scala-java-build succeeds
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install requests
          pip install duckdb
      - name: Test Tutorial
        run: |
          source venv/bin/activate
          python tests/test_tutorial.py